import torch
from habitat_sim.utils.common import d3_40_colors_rgb

semantic_label_to_id = {
    'wall': 1,
    'floor': 2,
    'chair': 3,
    'door': 4,
    'table': 5,
    'picture': 6,
    'cabinet': 7,
    'cushion': 8,
    'window': 9,
    'sofa': 10,
    'bed': 11,
    'curtain': 12,
    'chest_of_drawers': 13,
    'plant': 14,
    'sink': 15,
    'stairs': 16,
    'ceiling': 17,
    'toilet': 18,
    'stool': 19,
    'towel': 20,
    'mirror': 21,
    'tv_monitor': 22,
    'shower': 23,
    'column': 24,
    'bathtub': 25,
    'counter': 26,
    'fireplace': 27,
    'lighting': 28,
    'beam': 29,
    'railing': 30,
    'shelving': 31,
    'blinds': 32,
    'gym_equipment': 33,
    'seating': 34,
    'board_panel': 35,
    'furniture': 36,
    'appliances': 37,
    'clothes': 38,
    'objects': 39,
    'misc': 0,
}

semantic_id_to_label = {v: k for k, v in semantic_label_to_id.items()}

semantic_30_class_name_list = [
    "wall",
    "objects",
    "door",
    "chair",
    "floor",
    "misc",
    "cushion",
    "table",
    "cabinet",
    "plant",
    "shelving",
    "mirror",
    "chest_of_drawers",
    "towel",
    "stairs",
    "railing",
    "column",
    "counter",
    "stool",
    "bed",
    "sofa",
    "appliances",
    "toilet",
    "tv_monitor",
    "seating",
    "clothes",
    "fireplace",
    "bathtub",
    "furniture",
    "blinds",
]

semantic_22_class_name_list = [
    "wall",
    "objects",
    "door",
    "chair",
    "floor",
    "misc",
    "cushion",
    "table",
    "cabinet",
    "plant",
    "shelving",
    "mirror",
    "chest_of_drawers",
    "stairs",
    "railing",
    "column",
    "counter",
    "bed",
    "sofa",
    "seating",
    "clothes",
    "bathtub",
]

semantic_22_class_id_list = [semantic_label_to_id[label] - 1 for label in semantic_22_class_name_list]
semantic_30_class_id_list = [semantic_label_to_id[label] for label in semantic_30_class_name_list]
semantic_40_class_id_list = list(range(40))
colors_rgb_tensor = torch.Tensor(d3_40_colors_rgb).permute(1, 0).unsqueeze(0).unsqueeze(-1).unsqueeze(-1) / 255.0
